% Configuration for techsweep.m
% Boris Murmann
% Stanford University
function c = techsweep_config_bsim3_180_hspice

% Models and file paths
c.modelfile = './models/ee214_hspice.sp';
c.modelinfo = 'Stanford EE214B models, 180nm CMOS, BSIM3';
c.modeln = 'nmos214';
c.modelp = 'pmos214';
c.savefilen = '180nch';
c.savefilep = '180pch';
c.simcmd = '/cad/synopsys/hspice/H-2013.03-SP2/hspice/bin/hspice techsweep.sp >! techsweep.out';
c.outfile = 'techsweep.sw0';

% Sweep parameters
c.VGS_step = 25e-3;
c.VDS_step = 25e-3;
c.VSB_step = 100e-3;
c.VGS_max = 1.8;
c.VDS_max = 1.8;
c.VSB_max = 1.0;
c.VGS = 0:c.VGS_step:c.VGS_max;
c.VDS = 0:c.VDS_step:c.VDS_max;
c.VSB = 0:c.VSB_step:c.VSB_max;
c.LENGTH = [(0.18:0.02:0.5) (0.6:0.1:1.0)];
c.WIDTH = 5;
c.NFING = 1;

% Variable definitions
c.nvars = {'n_id', 'n_vt', 'n_gm', 'n_gmb', 'n_gds', 'n_cgg', 'n_cgs', 'n_cgd', 'n_cgb', 'n_cdd', 'n_css'}; 
c.pvars = {'p_id', 'p_vt', 'p_gm', 'p_gmb', 'p_gds', 'p_cgg', 'p_cgs', 'p_cgd', 'p_cgb', 'p_cdd', 'p_css'}; 
c.outvars = {'ID', 'VT', 'GM', 'GMB', 'GDS', 'CGG', 'CGS', 'CGD', 'CGB', 'CDD', 'CSS'};

% Simulation netlist
netlist = sprintf([...
'techsweep.sp \n'...
'.inc %s \n'...
'.inc techsweep_params.sp \n'...
'vdsn     vdn 0         dc ''ds''  \n'...
'vgsn     vgn 0         dc ''gs''  \n'...
'vbsn     vbn 0         dc ''-sb'' \n'...
'vdsp     vdp 0         dc ''-ds'' \n'...
'vgsp     vgp 0         dc ''-gs'' \n'...
'vbsp     vbp 0         dc ''sb''  \n'...
'mn       vdn vgn 0 vbn %s  L=''length*1e-6'' W=%d \n'...
'mp       vdp vgp 0 vbp %s  L=''length*1e-6'' W=%d \n'...
'.options dccap post brief accurate \n'...
'\n'...
'.dc gs 0 %d %d ds 0 %d %d \n'...
'\n'...
'.probe n_id   = par(''i(mn)'') \n'...
'.probe n_vt   = par(''vth(mn)'') \n'...
'.probe n_gm   = par(''gmo(mn)'')   \n'...
'.probe n_gmb  = par(''gmbso(mn)'') \n'...
'.probe n_gds  = par(''gdso(mn)'')  \n'...
'.probe n_cgg  = par(''cggbo(mn)'') \n'...
'.probe n_cgs  = par(''-cgsbo(mn)'') \n'...
'.probe n_cgd  = par(''-cgdbo(mn)'') \n'...
'.probe n_cgb  = par(''cggbo(mn)-(-cgsbo(mn))-(-cgdbo(mn)) '') \n'...
'.probe n_cdd  = par(''cddbo(mn)'') \n'...
'.probe n_css  = par(''-cgsbo(mn)-cbsbo(mn)'') \n'...
'\n'...
'.probe p_id   = par(''-i(mp)'') \n'...
'.probe p_vt   = par(''vth(mp)'') \n'...
'.probe p_gm   = par(''gmo(mp)'') \n'...
'.probe p_gmb  = par(''gmbso(mp)'') \n'...
'.probe p_gds  = par(''gdso(mp)'') \n'...
'.probe p_cgg  = par(''cggbo(mp)'') \n'...
'.probe p_cgs  = par(''-cgsbo(mp)'') \n'...
'.probe p_cgd  = par(''-cgdbo(mp)'') \n'...
'.probe p_cgb  = par(''cggbo(mp)-(-cgsbo(mp))-(-cgdbo(mp)) '') \n'...
'.probe p_cdd  = par(''cddbo(mp)'') \n'...
'.probe p_css  = par(''-cgsbo(mp)-cbsbo(mp)'') \n'...
'.end \n'...
], c.modelfile, ...
c.modeln, c.WIDTH*1e-6, ...
c.modelp, c.WIDTH*1e-6, ...
c.VGS_max, c.VGS_step, ...
c.VDS_max, c.VDS_step);

% Write netlist
fid = fopen('techsweep.sp', 'w');
fprintf(fid, netlist);
fclose(fid);

return



